/*
*  This file is part of aasdk library project.
*  Copyright (C) 2018 f1x.studio (Michal Szwaj)
*
*  aasdk is free software: you can redistribute it and/or modify
*  it under the terms of the GNU General Public License as published by
*  the Free Software Foundation; either version 3 of the License, or
*  (at your option) any later version.

*  aasdk is distributed in the hope that it will be useful,
*  but WITHOUT ANY WARRANTY; without even the implied warranty of
*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*  GNU General Public License for more details.
*
*  You should have received a copy of the GNU General Public License
*  along with aasdk. If not, see <http://www.gnu.org/licenses/>.
*/

syntax="proto2";

option optimize_for=SPEED;

import "proto/service/sensor/SensorService.proto";
import "proto/service/media/sink/MediaSinkService.proto";
import "proto/service/input/InputService.proto";
import "proto/service/media/source/MediaSourceService.proto";
import "proto/service/bluetooth/BluetoothService.proto";
import "proto/service/navigation/NavigationService.proto";
import "proto/service/vendorextension/VendorExtensionService.proto";
import "proto/service/wifiprojection/WifiProjectionService.proto";
import "proto/service/mediabrowser/MediaBrowserService.proto";
import "proto/service/genericnotification/GenericNotificationService.proto";
import "proto/service/phonestatus/PhoneStatusService.proto";
import "proto/service/mediaplayback/MediaPlaybackStatusService.proto";
import "proto/service/radio/RadioService.proto";

package aasdk.proto.service;

message ServiceDescriptor
{
    required uint32 channel_id = 1;
    optional sensor.SensorService sensor_service = 2;
    optional media.sink.MediaSinkService media_sink_service = 3;
    optional input.InputSourceService input_service = 4;
    optional media.source.MediaSourceService media_source_service = 5;
    optional bluetooth.BluetoothService bluetooth_service = 6;
    optional radio.RadioService radio_service = 7;
    optional navigation.NavigationService navigation_service = 8;
    optional mediaplayback.MediaPlaybackStatusService media_playback_status_service = 9;
    optional phonestatus.PhoneStatusService phone_status_service = 10;
    optional mediabrowser.MediaBrowserService media_browser_service = 11;
    optional vendorextension.VendorExtensionService vendor_extension_service = 12;
    optional genericnotification.GenericNotificationService generic_notification_service = 13;
    optional wifiprojection.WifiProjectionService wifi_projection_service = 14;
}
