syntax="proto2";

import "aap_protobuf/service/input/FeedbackEventType.proto";
import "aap_protobuf/service/input/message/TouchPad.proto";
import "aap_protobuf/service/input/message/TouchScreen.proto";

package aap_protobuf.service.input;

message InputSourceService
{
    repeated uint32 supported_keycodes = 1 [packed = true];
    repeated message.TouchScreen touchscreen = 2;
    repeated message.TouchPad touchpad = 3;
    repeated FeedbackEventType feedback_events_types_supported = 4;
    optional uint32 display_id = 5;
}
