/*
*  This file is part of aasdk library project.
*  Copyright (C) 2018 f1x.studio (Michal Szwaj)
*
*  aasdk is free software: you can redistribute it and/or modify
*  it under the terms of the GNU General Public License as published by
*  the Free Software Foundation; either version 3 of the License, or
*  (at your option) any later version.

*  aasdk is distributed in the hope that it will be useful,
*  but WITHOUT ANY WARRANTY; without even the implied warranty of
*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*  GNU General Public License for more details.
*
*  You should have received a copy of the GNU General Public License
*  along with aasdk. If not, see <http://www.gnu.org/licenses/>.
*/

syntax="proto2";

package aap_protobuf.service.navigation;


enum NavigationChannelMessageId
{
  INSTRUMENT_CLUSTER_START = 32769;
  INSTRUMENT_CLUSTER_STOP = 32770;
  INSTRUMENT_CLUSTER_NAVIGATION_STATUS = 32771;
  INSTRUMENT_CLUSTER_NAVIGATION_TURN_EVENT = 32772 [deprecated = true];
  INSTRUMENT_CLUSTER_NAVIGATION_DISTANCE_EVENT = 32773 [deprecated = true];
  INSTRUMENT_CLUSTER_NAVIGATION_STATE = 32774;
  INSTRUMENT_CLUSTER_NAVIGATION_CURRENT_POSITION = 32775;
}
