/*
*  This file is part of aasdk library project.
*  Copyright (C) 2018 f1x.studio (Michal Szwaj)
*
*  aasdk is free software: you can redistribute it and/or modify
*  it under the terms of the GNU General Public License as published by
*  the Free Software Foundation; either version 3 of the License, or
*  (at your option) any later version.

*  aasdk is distributed in the hope that it will be useful,
*  but WITHOUT ANY WARRANTY; without even the implied warranty of
*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*  GNU General Public License for more details.
*
*  You should have received a copy of the GNU General Public License
*  along with aasdk. If not, see <http://www.gnu.org/licenses/>.
*/

syntax="proto2";

package aap_protobuf.service.media.shared.message;

enum MediaCodecType
{
    MEDIA_CODEC_AUDIO_PCM = 1;
    MEDIA_CODEC_AUDIO_AAC_LC = 2;
    MEDIA_CODEC_VIDEO_H264_BP = 3;
    MEDIA_CODEC_AUDIO_AAC_LC_ADTS = 4;
    MEDIA_CODEC_VIDEO_VP9 = 5;
    MEDIA_CODEC_VIDEO_AV1 = 6;
    MEDIA_CODEC_VIDEO_H265 = 7;
}
