/*
*  This file is part of aasdk library project.
*  Copyright (C) 2018 f1x.studio (Michal Szwaj)
*
*  aasdk is free software: you can redistribute it and/or modify
*  it under the terms of the GNU General Public License as published by
*  the Free Software Foundation; either version 3 of the License, or
*  (at your option) any later version.

*  aasdk is distributed in the hope that it will be useful,
*  but WITHOUT ANY WARRANTY; without even the implied warranty of
*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*  GNU General Public License for more details.
*
*  You should have received a copy of the GNU General Public License
*  along with aasdk. If not, see <http://www.gnu.org/licenses/>.
*/

syntax="proto2";

package aap_protobuf.service.media.shared.message;

enum VideoCodecResolutionType {
  VIDEO_800x480 = 1;
  VIDEO_1280x720 = 2;
  VIDEO_1920x1080 = 3;
  VIDEO_2560x1440 = 4;
  VIDEO_3840x2160 = 5;
  VIDEO_720x1280 = 6;
  VIDEO_1080x1920 = 7;
  VIDEO_1440x2560 = 8;
  VIDEO_2160x3840 = 9;
}
