/*
*  This file is part of aasdk library project.
*  Copyright (C) 2018 f1x.studio (Michal Szwaj)
*
*  aasdk is free software: you can redistribute it and/or modify
*  it under the terms of the GNU General Public License as published by
*  the Free Software Foundation; either version 3 of the License, or
*  (at your option) any later version.

*  aasdk is distributed in the hope that it will be useful,
*  but WITHOUT ANY WARRANTY; without even the implied warranty of
*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*  GNU General Public License for more details.
*
*  You should have received a copy of the GNU General Public License
*  along with aasdk. If not, see <http://www.gnu.org/licenses/>.
*/

syntax="proto2";

import "aap_protobuf/service/ServiceDescriptor.proto";
import "aap_protobuf/connection/ConnectionConfiguration.proto";
import "aap_protobuf/channel/control/servicediscovery/notification/DriverPosition.proto";

package aap_protobuf.channel.control.servicediscovery.notification;

message ServiceDiscoveryResponse
{
    repeated service.ServiceDescriptor channels = 1;
    optional string make = 2 [deprecated = true];
    optional string model = 3 [deprecated = true];
    optional string year = 4 [deprecated = true];
    optional string vehicle_id = 5 [deprecated = true];
    optional notification.DriverPosition driver_position = 6;
    optional string head_unit_make = 7 [deprecated = true];
    optional string head_unit_model = 8 [deprecated = true];
    optional string head_unit_software_build = 9 [deprecated = true];
    optional string head_unit_software_version = 10 [deprecated = true];
    optional bool can_play_native_media_during_vr = 11 [deprecated = true];
    optional int32 session_configuration = 13;
    optional string display_name = 14;
    optional bool probe_for_support = 15;
    optional connection.ConnectionConfiguration connection_configuration = 16;
    optional HeadUnitInfo headunit_info = 17;
}

message HeadUnitInfo {
    optional string make = 1;
    optional string model = 2;
    optional string year = 3;
    optional string vehicle_id = 4;
    optional string head_unit_make = 5;
    optional string head_unit_model = 6;
    optional string head_unit_software_build = 7;
    optional string head_unit_software_version = 8;
}

